spring:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:mem:booklibrary
    #    tcp: jdbc:h2:tcp://localhost:9092/mem:booklibrary
    username: sa
    password:
  h2.console.enabled: true